version: "3.1"

services:
  pact-stub-server-json:
    build:
      context: pact-stub-service
      args:
        PACT_FILE: pacts/test-consumer-json-provider.json
    ports:
      - "8080:8080"
  pact-stub-server-file-upload:
    build:
      context: pact-stub-service
      args:
        PACT_FILE: pacts/test-consumer-file-upload-provider.json
    ports:
      - "8081:8080"
  pact-stub-server-soap:
    build:
      context: pact-stub-service
      args:
        PACT_FILE: pacts/test-consumer-soap-provider.json
    ports:
      - "8082:8080"
  pact-stub-server-aws:
    build:
      context: pact-stub-service
      args:
        PACT_FILE: pacts/test-consumer-aws-provider.json
    ports:
      - "8083:8080"

  